
package expenses;
import java.sql.PreparedStatement;
import JDBC.DBConn;
import main.DashboardForm;
import main.QueryInterfce;
import report.ReportForm;
import main.User;
import expenseCategories.Category;
import expenseCategories.ExpenseCategoryForm;
import income.IncomeForm;
import incomeCategories.IncomeCategoryForm;



import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

import java.util.HashMap;
import java.util.Locale;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.lang.model.type.TypeKind.NULL;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class MainFrame1 extends javax.swing.JFrame implements QueryInterfce{
    Statement stmt = null;
    Statement stmt1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    DBConn conn=new DBConn();
    Connection con=conn.getConnection();
    private TreeMap <Integer, String> categoryMap = new TreeMap<Integer, String>();
    
    /**
     * Creates new form ExpenseForm
     */
    public MainFrame1() {
        initComponents();
        populateCombo1();
        showDataE();
        ID.setVisible(false);
        setLocation(275, 53);
        setSize(1480, 1000); 
        
        
//        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
   
        private void executeSQLQuery(String query, String message) {
        

        try {
            stmt=con.createStatement();
            if(stmt.executeUpdate(query)==1){
                 DefaultTableModel model=(DefaultTableModel)jTableExpenses.getModel();
                model.setRowCount(0);
                showDataE();
                JOptionPane.showMessageDialog(null, message);
                
            }else{
                JOptionPane.showMessageDialog(null,"Data not inserted ");
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(IncomeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public HashMap<String, Integer> populateCombo1(){
        
            HashMap<String, Integer> map=new HashMap<String, Integer>();
            
           
           
            try {
            String query="select id, name from categories";
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
//            Category category;

            while(rs.next()){
                 int id = rs.getInt("id");
                 String name = rs.getString("name");
                 System.out.println(name);
                 
                categories1.addItem(name);
                //categoryMap.put(rs.getInt("id"), name);

//                categories.addItem(rs.getInt("id"));
//                category=new Category(rs.getInt(0),rs.getString(1));
//                map.put(category.getName(), category.getId());
            }
          
            } catch (SQLException ex) {
               java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        return map;
    } 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        description1 = new javax.swing.JTextField();
        categories1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantity1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbl_session_user_id = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        date2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExpenses = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(247, 225, 211));

        jPanel2.setBackground(new java.awt.Color(247, 225, 211));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 61, 63));
        jLabel1.setText("Title");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 61, 63));
        jLabel2.setText("Description ");

        categories1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categories1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 61, 63));
        jLabel3.setText("Categories");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(55, 61, 63));
        jLabel4.setText("Quantity");

        quantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 61, 63));
        jLabel5.setText("Amount");

        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(247, 225, 211));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(55, 61, 63));
        jLabel8.setText("Date");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(459, 459, 459)
                                .addComponent(lbl_session_user_id)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(description1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(categories1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantity1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(title1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_session_user_id)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(categories1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addComponent(quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(clear))
                .addGap(37, 37, 37))
        );

        jPanel4.setBackground(new java.awt.Color(179, 160, 145));

        jLabel7.setBackground(new java.awt.Color(179, 160, 145));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 80)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Expenses Form");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addGap(61, 61, 61))
        );

        jTableExpenses.setBackground(new java.awt.Color(195, 207, 160));
        jTableExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Category", "Quantity", "Amount", "Date"
            }
        ));
        jTableExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExpenses);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE))
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(744, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity1ActionPerformed

    private void categories1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categories1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categories1ActionPerformed
    public ArrayList<Expense> getExpenseList(){
        ArrayList<Expense> expenseList=new ArrayList<Expense>();
       
        String query="SELECT expenses.id, expenses.user_id,expenses.name, expenses.category_id, categories.name as category,expenses.description, expenses.quantity,expenses.cost,expenses.date,expenses.user_id FROM expenses LEFT JOIN categories ON expenses.category_id=categories.id where expenses.user_id='"+User.getUser_session_id()+"' "; 
       
        try{
            stmt=con.createStatement();
            rs=stmt.executeQuery(query);
            
            Expense expense;
           
            while(rs.next()){
               
                expense=new Expense(rs.getInt("id"),rs.getInt("quantity"),rs.getString("category"),rs.getInt("cost"),rs.getString("name"),rs.getString("description"),rs.getDate("date"));
                System.out.println(rs.getString("date"));
                expenseList.add(expense);
            }          
        }catch(Exception error){
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
         
        return expenseList;
    }
    
    public void showDataE(){
        ArrayList<Expense> list =getExpenseList();
      
        DefaultTableModel model=(DefaultTableModel) jTableExpenses.getModel();
        Object[] row=new Object[7];
        for(int i=0;i<list.size();i++){
            
            
            row[0]=list.get(i).getId();             
            row[1]=list.get(i).getTitle(); 
            row[2]=list.get(i).getDescription(); 
            row[3]=list.get(i).getCategory();
            row[4]=list.get(i).getQuantity();
            row[5]=list.get(i).getCost();
            row[6]=list.get(i).getDate();
            model.addRow(row);

        }
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        Integer users=User.user_session_id;       
//        lbl_session_user_id.setText(String.valueOf(User.getUser_session_id()));
//        String session_user_id=lbl_session_user_id.getText();
        Integer session_user_id=User.getUser_session_id();
        SimpleDateFormat dd=new SimpleDateFormat("Y-MM-dd");
        String ddd=dd.format(date2.getCalendar().getTime());
//        System.out.println("which id"+categories.getSelectedItem().categories.id);
       
        try {
//            sql query for geting the specific item that we have selected
            String query=" SELECT id from categories where name = '"+categories1.getSelectedItem().toString()+"' ";
            stmt1=con.createStatement();
            rs1=stmt1.executeQuery(query);
            rs1.next();
//            get the selected id 
            Integer sum=rs1.getInt(1);
            System.out.println("result "+sum);
//          Converstion of int to string
            String convertSum = Integer.toString(sum);
            // sql query for inserting expenses data
            String query1 ="insert into expenses(name,description,category_id,quantity,cost,date,user_id) values('"+title1.getText()+"','"+description1.getText()+"','"+convertSum+"','"+Integer.parseInt(quantity1.getText())+"','"+Float.parseFloat(amount1.getText())+"','"+ddd+"','"+User.getUser_session_id()+"')";
            
            
            String message="Successfully inserted data";
            executeSQLQuery(query1, message);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
//        
//        
//        
//        
//        
//        
//        
//        

        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String query="delete from expenses where id= '"+ID.getText()+"' "  ;
            conn.executeSQLQuery1(this,query, "Successfully deleted");
    }//GEN-LAST:event_deleteActionPerformed

    private void jTableExpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExpensesMouseClicked
        // TODO add your handling code here:
        int i=jTableExpenses.getSelectedRow();
        TableModel model=jTableExpenses.getModel();
        ID.setText(model.getValueAt(i,0).toString());
        title1.setText(model.getValueAt(i,1).toString());
        description1.setText(model.getValueAt(i,2).toString());   
        categories1.setSelectedItem(model.getValueAt(i,3));
        quantity1.setText(model.getValueAt(i,4).toString());
        amount1.setText(model.getValueAt(i,5).toString());
        date2.setDate((java.util.Date) model.getValueAt(i,6));
        
    }//GEN-LAST:event_jTableExpensesMouseClicked

     
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(title1.getText().trim().isEmpty()){
          
        }else{
            SimpleDateFormat dd=new SimpleDateFormat("Y-MM-dd");
            String dates=dd.format(date2.getCalendar().getTime());
            System.out.println(dates);
            String query="update expenses set name='"+title1.getText()+"', description='"+description1.getText()+"' , category_id='"+categories1.getSelectedIndex()+"', quantity='"+Integer.parseInt(quantity1.getText())+"',cost='"+Float.parseFloat(amount1.getText())+"',date='"+dates+"'  where id= '"+ID.getText()+"' ";
            System.out.println(query);
            conn.executeSQLQuery1(this,query, "Updated successfully");
           
        }
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        new MainFrame1().setVisible(true);
        dispose();
    }//GEN-LAST:event_clearActionPerformed

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField amount1;
    private javax.swing.JComboBox<String> categories1;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton delete;
    private javax.swing.JTextField description1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExpenses;
    private javax.swing.JLabel lbl_session_user_id;
    private javax.swing.JTextField quantity1;
    private javax.swing.JTextField title1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onQueryExec(String message) {
        DefaultTableModel model=(DefaultTableModel)jTableExpenses.getModel();
        model.setRowCount(0);
        showDataE();
        JOptionPane.showMessageDialog(null, message);
    }

    @Override
    public void onError(String message) {
        JOptionPane.showMessageDialog(null,message);
    }

  
}
